### ISSUE TITLE
Backend: Main App Creation

### ISSUE THREAD

**Issue by zguo123** [Lu-Entertainment/utmcfsa.org#15]
### **Important Notice**
You must consider and think before doing the task for the backend. We must follow the **Test-Driven Development** Model for all back-end items. In essence, we must follow the steps outlined below: 

3. Add tests to file `tests.py.`
4. Edit the `views.py` file 

**Note:** Under this model, do **NOT** create views before creating the test cases. 

### **Tasks**

- [x] Setup form app using: `django-admin startapp main` in the `studentcentre` directory. 
- [x] Create the URLs file
- [x] Add tests to file `tests.py`
- [x] Edit the `views.py`, `models.py` and create `serializers.py' files 
- [x] Add the URLs to the root `studentcentre` directory
- [x] Add entries to `admin.py` in the app folder.
