### ISSUE TITLE
Backend: Implementation of form sending and collaborators 

### ISSUE THREAD

**Issue by zguo123** [Lu-Entertainment/utmcfsa.org#22]
### **Important Notice**
You must consider and think before doing the task for the backend. We must follow the **Test-Driven Development** Model for all back-end items. In essence, we must follow the steps outlined below: 

3. Add tests to file `tests.py.`
4. Edit the `views.py` file 

**Note:** Under this model, do **NOT** create views before creating the test cases. 

### **Tasks**
- [ ] Create the URLs file
- [ ] Add tests to file `tests.py`
- [ ] Edit `views.py` file
- [ ] Modify the URLs to the root `studentcentre` directory
