### ISSUE TITLE
Extending the Search Function

### ISSUE THREAD

**Issue by zguo123** [Lu-Entertainment/utmcfsa.org#4]
### **Important Notes**
This task is very challenging. For this task, you must decide how to display what and how to display the categories.
However, you must make sure that the design does not break the page's continuity as a whole. 
 
### **Tasks**
- [ ]  Decide on the design elements (how to style, actions, etc...) 
- [ ]  Decide on the filters
- [ ] Implementation of the fliters
