### ISSUE TITLE
Finalize overall frontend design

### ISSUE THREAD

**Issue by zguo123** [Lu-Entertainment/utmcfsa.org#8]
### **Important Notice**
For this task, we must make decisions such as: 
- How many error pages we include
- Necessary links for all the survey routes. 

### **Tasks**
- [ ] Make sure every link works
- [ ] Add necessary links to all the pages
- [ ] Add pages for the 404 error page, 500 errors.
